set shell := ["bash", "-cu"]

default: dev

# ------------- dev/build/run -------------

dev:
    pnpm dev

build:
    pnpm build

start:
    pnpm start

# ------------- quality gates -------------

typecheck:
    pnpm typecheck

lint:
    pnpm lint:fix

format:
    pnpm format

check: format lint typecheck

# ------------- utilities -------------
clean:
    pnpm clean

analyze:
    pnpm analyze
