"""Manicure — provider-neutral context control plane for coding agents."""

from __future__ import annotations

# Version resolution order:
# 1. The file generated by hatch-vcs during `uv build` / `pip install` (always
#    accurate for shipped artifacts, including editable installs).
# 2. Python package metadata (for environments where the file is missing but
#    the package is installed through some other path).
# 3. A sentinel string so imports never crash during bare source checkouts.
try:
    from ._version import __version__
except ImportError:  # pragma: no cover — exercised only on pristine checkouts
    try:
        from importlib.metadata import PackageNotFoundError, version

        __version__ = version("manicure")
    except PackageNotFoundError:
        __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
